apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: admin
      port: {{ .Values.service.port }}
      targetPort: admin
      protocol: TCP
