apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: garage
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  garage.toml: |
    metadata_dir = "{{ .Values.persistence.meta.mountPath }}"
    data_dir = "{{ .Values.persistence.data.mountPath }}"
    db_engine = "{{ .Values.config.metadataEngine }}"

    replication_factor = {{ .Values.config.replicationMode }}

    rpc_bind_addr = "[::]:{{ .Values.service.rpc.port }}"

    [s3_api]
    s3_region = "{{ .Values.config.s3Region }}"
    api_bind_addr = "[::]:{{ .Values.service.s3.port }}"

    [s3_web]
    bind_addr = "[::]:{{ .Values.service.web.port }}"
    root_domain = ".s3.internal.lab.infiniteroomlabs.cloud"

    [admin]
    api_bind_addr = "[::]:{{ .Values.service.admin.port }}"
